"use client";
import { useState } from "react";
import type { BankFeedPublic } from "@/server/bank-feed";
import { Button } from "@/components/ui/button";
import { Field, Input } from "@/components/ui/input";

export function BankFeedForm({ feed }: { feed: BankFeedPublic }) {
  const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(action: "save"|"sync"|"delete", form?: HTMLFormElement) { setBusy(true); setMessage(""); try { const body = form ? Object.fromEntries(new FormData(form)) : {}; const response = await fetch("/api/v1/bank-feed", { method: action === "delete" ? "DELETE" : "POST", headers: { "content-type":"application/json" }, body: action === "delete" ? undefined : JSON.stringify(action === "sync" ? { action } : { ...body, enabled: true, sync_interval_minutes: Number(body.sync_interval_minutes) }) }); const result = await response.json(); if(!response.ok) throw new Error(result.error||"Request failed"); setMessage(action === "sync" ? `Imported ${result.imported}; matched ${result.matched}; left ${result.ambiguous} unmatched.` : action === "delete" ? "Bank feed disconnected." : "Bank feed saved."); window.location.reload(); } catch(e) { setMessage(e instanceof Error ? e.message : "Request failed"); } finally { setBusy(false); } }
  return <div><form onSubmit={(e)=>{e.preventDefault();void submit("save",e.currentTarget);}} className="grid max-w-xl gap-4 sm:grid-cols-2"><div><Field label="RazorpayX account number"><Input name="account_number" inputMode="numeric" placeholder={feed.configured ? "••••••••••••" : "7878780080316316"}/></Field><p className="mt-1 text-xs text-muted-foreground">{feed.configured ? `Saved account ending ${feed.account_last4}. Leave blank to keep it.` : "Shown in RazorpayX Banking."}</p></div><Field label="Automatic sync"><select name="sync_interval_minutes" defaultValue={feed.sync_interval_minutes} className="h-10 rounded-xl border border-input bg-background px-3 text-sm"><option value="15">Every 15 minutes</option><option value="60">Every hour</option><option value="360">Every 6 hours</option><option value="1440">Daily</option></select></Field><div className="flex flex-wrap gap-2 sm:col-span-2"><Button disabled={busy}>{feed.configured ? "Update bank feed" : "Connect bank feed"}</Button>{feed.configured?<><Button type="button" variant="outline" disabled={busy} onClick={()=>void submit("sync")}>Sync now</Button><Button type="button" variant="outline" disabled={busy} onClick={()=>void submit("delete")}>Disconnect</Button></>:null}</div></form>{feed.last_synced_at?<p className="mt-3 text-xs text-muted-foreground">Last synced {new Date(feed.last_synced_at).toLocaleString("en-IN")}.</p>:null}{feed.last_error?<p className="mt-2 text-sm text-bad">{feed.last_error}</p>:null}{message?<p className="mt-3 text-sm" role="status">{message}</p>:null}</div>;
}
